version: "4"
services:
    api:
        image: iadiee/fastapi
        depends_on:
          - postgres
        ports:
          - 80:8000

#        command: uvicorn main:app --host 0.0.0.0 --port 8000

        environment:
           - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
           - DATABASE_PORT=${DATABASE_PORT}
           - DATABASE_PASSWORD=${DATABASE_PASSWORD}
           - DATABASE_NAME=${DATABASE_NAME}
           - DATABASE_USERNAME=${DATABASE_USERNAME}
           - SECRET_KEY=${SECRET_KEY}
           - ALGORITHM=${ALGORITHM}
           - TIME_AT_EXPIRATION=${TIME_AT_EXPIRATION}
    postgres:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      volumes:
        - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db:

