version: "4"
services:
    api:
        build: .
        depends_on:
          - postgres
        ports:
          - 8000:8000
        volumes:
          - ./:/usr/src/app:ro
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

        environment:
           - DATABASE_HOSTNAME=postgres
           - DATABASE_PORT=5432
           - DATABASE_PASSWORD=Adithya1
           - DATABASE_NAME=fastappi
           - DATABASE_USERNAME=postgres
           - SECRET_KEY=F1D42872D4639332A11923B1DA7557DC40CD97F4442BB802CC0826C5A0010BCD
           - ALGORITHM=HS256
           - TIME_AT_EXPIRATION=30
    postgres:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=Adithya1

      volumes:
        - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db:

