name: Build and Deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v4
      - name: say Hello
        run: echo "Hello iadiee"